# -*- coding: utf-8 -*-
"""pacmann-super-cashier

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Efied5O1up99cua9pdhsHuksNd21tSje
"""

# Membuat kode untuk ID customer

print ('Selamat datang di Toserba Andi \n')

nama = (input('Masukkan nama Anda : \n'))

'''\n
'''

if nama == 'nisa' or nama == 'superadmin':
  print (f'Selamat datang, Superadmin {nama}! \n') 
else: 
  print (f'Selamat datang, customer {nama}! \n')

def garis ():
    print('=========================================================== \n')

garis()

# Membuat daftar barang dan harga berdasarkan kode 

def transaksi():
      print ('''\t DAFTAR BARANG TOSERBA ANDI
    -------------------------------------- 
    A. Fashion and Lifestyle 
    1. Jilbab paris \t 41000
    2. Celana joger \t 54000
    3. Kaos polos \t 50000

    B. Food and Beverages
    4. Air mineral \t 10000
    5. Kopi susu  \t 56000
    6. Donat ktg \t 34000
    7. Rice bowl   \t 75000

    C. Vegetables and Meat
    8. Jamur enoki \t 18000
    9. Selada hijau \t 16000
    10. Dada ayam  \t 65000

    --------------------------------------
    ''')

transaksi()

jumlah_transaksi = int(input('Masukkan total jenis belanjaan Anda : '))

kode = []
barang = []
harga = []
qty = []
jumlah = []

b = 0
while b<jumlah_transaksi:
  print('Pembelian ke-',b+1)
    
# Membuat kode input barang secara manual dengan append 

  kode.append(int(input('Masukkan kode barang : ')))
  qty.append(int(input('Masukkan jumlah barang : ')))
  if kode[b] == 1:
      barang.append('Jilbab paris')
      harga.append(41000)
      jumlah.append(qty[b]*int(41000))
  elif kode[b] == 2:
        barang.append('Celana joger')
        harga.append(54000)
        jumlah.append(qty[b]*int(54000))
  elif kode[b] == 3:
        barang.append('Kaos polos')
        harga.append(50000)
        jumlah.append(qty[b]*int(50000))
  elif kode[b] == 4:
        barang.append('Air mineral')
        harga.append(10000)
        jumlah.append(qty[b]*int(10000))
  elif kode[b] == 5:
        barang.append('Kopi susu')
        harga.append(56000)
        jumlah.append(qty[b]*int(56000))
  elif kode[b] == 6:
        barang.append('Donat ktg')
        harga.append(34000)
        jumlah.append(qty[b]*int(34000))
  elif kode[b] == 7:
        barang.append('Rice bowl')
        harga.append(75000)
        jumlah.append(qty[b]*int(75000))
  elif kode[b] == 8:
        barang.append('Jamur enoki')
        harga.append(18000)
        jumlah.append(qty[b]*int(18000))
  elif kode[b] == 9:
        barang.append('Selada hijau')
        harga.append(16000)
        jumlah.append(qty[b]*int(16000))
  elif kode[b] == 10:
        barang.append('Dada ayam')
        harga.append(65000)
        jumlah.append(qty[b]*int(65000))
  else:
        barang.append ('Barang tidak ditemukan!')
        harga.append ('0')
        jumlah.append(qty[b]*int(0))
  b = b+1

garis ()

# Membuat kode cek transaksi 
  
def daftarbelanja():
    print ('\t \t Daftar Belanjaan Anda')
    print ('---------------------------------------------------------')
    print ('No |     Nama Barang    |   Harga   |  Qty  |   Subtotal' )
    print ('---------------------------------------------------------')

daftarbelanja()

total = 0
a = 0
while a<jumlah_transaksi:
    total = total + jumlah[a]
    print('%i \t %s  \t  %s \t %i \t %i'%(a+1, barang[a], harga[a], qty[a], jumlah[a]))
    a = a+1

garis ()

# Membuat kode untuk memastikan customer tentang belanjaannya

belanja = str(input('Apakah Anda ingin mengubah transaksi Anda? (y/t) : \n'))

if belanja == 't':
    print('Silakan melanjutkan pembayaran! \n')
    while belanja != 't':
      print ('Transaksi Anda telah dihapus')

garis()

transaksi()

jumlah_transaksi = int(input('Masukkan jumlah jenis belanjaan Anda : '))

kode = []
barang = []
harga = []
qty = []
jumlah = []

b = 0
while b<jumlah_transaksi:
  print('Pembelian ke-',b+1)
    
# Membuat kode input barang secara manual

  kode.append(int(input('Masukkan kode barang : ')))
  qty.append(int(input('Masukkan jumlah barang : ')))
  if kode[b] == 1:
      barang.append('Jilbab paris')
      harga.append(41000)
      jumlah.append(qty[b]*int(41000))
  elif kode[b] == 2:
        barang.append('Celana joger')
        harga.append(54000)
        jumlah.append(qty[b]*int(54000))
  elif kode[b] == 3:
        barang.append('Kaos polos')
        harga.append(50000)
        jumlah.append(qty[b]*int(50000))
  elif kode[b] == 4:
        barang.append('Air mineral')
        harga.append(10000)
        jumlah.append(qty[b]*int(10000))
  elif kode[b] == 5:
        barang.append('Kopi susu')
        harga.append(56000)
        jumlah.append(qty[b]*int(56000))
  elif kode[b] == 6:
        barang.append('Donat ktg')
        harga.append(34000)
        jumlah.append(qty[b]*int(34000))
  elif kode[b] == 7:
        barang.append('Rice bowl')
        harga.append(75000)
        jumlah.append(qty[b]*int(75000))
  elif kode[b] == 8:
        barang.append('Jamur enoki')
        harga.append(18000)
        jumlah.append(qty[b]*int(18000))
  elif kode[b] == 9:
        barang.append('Selada hijau')
        harga.append(16000)
        jumlah.append(qty[b]*int(16000))
  elif kode[b] == 10:
        barang.append('Dada ayam')
        harga.append(65000)
        jumlah.append(qty[b]*int(65000))
  else:
        barang.append ('Barang tidak ditemukan!')
        harga.append ('0')
        jumlah.append(qty[b]*int(0))
  b = b+1

garis ()

# Membuat ulang kode cek transaksi 
  
def daftarbelanja():
    print ('\t \t Daftar Belanjaan Anda')
    print ('---------------------------------------------------------')
    print ('No |     Nama Barang    |   Harga   |  Qty  |   Subtotal' )
    print ('---------------------------------------------------------')

daftarbelanja()

total = 0
a = 0
while a<jumlah_transaksi:
    total = total + jumlah[a]
    print('%i \t %s  \t  %s \t %i \t %i'%(a+1, barang[a], harga[a], qty[a], jumlah[a]))
    a = a+1

garis ()

# Membuat ulang kode untuk memastikan customer tentang belanjaannya

belanja = str(input('Apakah Anda ingin mengubah transaksi Anda? (y/t) : \n'))

if belanja == 't':
    print('Silakan melanjutkan pembayaran! \n')
    while belanja != 't':
      print ('Transaksi Anda telah dihapus')
      print('-------------------------------------------------------------')

garis ()

# Menghitung perolehan diskon 

def diskon(): 
    diskon = 0
    if (total > 200000) and (total <= 300000):
      total_akhir = total - (0.05 * total)
      print (f'Anda mendapatkan diskon 5%! Jumlah yang harus dibayar : {total_akhir}.')
    elif (total > 300000) and (total < 500000):
      total_akhir = total - (0.08 * total)
      print (f'Anda mendapatkan diskon 8%! Jumlah yang harus dibayar : {total_akhir}.')
    elif total > 500000:
      total_akhir = total - (0.1 * total)
      print (f'Anda mendapatkan diskon 10%! Jumlah yang harus dibayar : {total_akhir}.')
    else:
      total_akhir = total
      print ('Anda belum memenuhi persyaratan untuk mendapatkan diskon! Jumlah yang harus dibayar: ',total, "\n")

# Menghitung total pembayaran

print ('Total belanjaan Anda sebesar :', total)
diskon ()

garis ()

print('Terima kasih telah berbelanja di Toserba Andi! Selamat datang kembali!')